### ISSUE TITLE
Automake error

### ISSUE THREAD

**Issue by assombrance** [AdaCore/why3#4]
The automake step of the installation (`automake --add-missing`) returns the following error:
`automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.in: You should verify that configure.in invokes AM_INIT_AUTOMAKE,
configure.in: that aclocal.m4 is present in the top-level directory,
configure.in: and that aclocal.m4 was recently regenerated (using aclocal)
configure.in:171: installing './install-sh'
automake: error: no 'Makefile.am' found for any configure output`

I am trying to make a Dockerfile for Why3, and this is preventing the build process to carry on. 

I found a way to ignore the error (appending `; exit 0` behind the command) but it seems very dirty).

This error is not blocking (after running the command, the other steps run properly) but it seems that there you be a better way to handle this ...

Thanks in advance.

**Comment by kanigsson** [comment]
Hello, you should submit your report to the official why3 repository at https://gitlab.inria.fr/why3/why3. This repository here is a clone for the version of why3 inside SPARK. We will update the README of our clone to reflect that (I will leave the issue open for this action).

**Comment by kanigsson** [comment]
We have now updated the README file.
